# Generated by Django 2.2.1 on 2019-07-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GoogleQueryAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('debate_worthy', models.BinaryField()),
                ('topic_label', models.CharField(max_length=50)),
                ('annotation_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GoogleQueryAnnotationSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('instruction_complete', models.BooleanField(default=False)),
                ('job_complete', models.BooleanField(default=False)),
                ('jobs', models.TextField()),
                ('finished_jobs', models.TextField()),
                ('duration', models.DurationField()),
                ('last_start_time', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleQueryBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ids', models.TextField(default='[]')),
                ('assign_count', models.IntegerField(default=0)),
                ('finish_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
