# Generated by Django 2.2.1 on 2019-07-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlequeryannotation',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='googlequeryannotation',
            name='query_id',
            field=models.IntegerField(default=-1),
        ),
    ]
