# Generated by Django 2.2.1 on 2019-07-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190717_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlequeryannotation',
            name='annotation_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='googlequeryannotation',
            name='topic_label',
            field=models.CharField(max_length=100),
        ),
    ]
