# Generated by Django 2.2.1 on 2019-07-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190717_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlequeryannotation',
            name='debate_worthy',
            field=models.BooleanField(),
        ),
    ]
